### ISSUE TITLE
Any shortcut to invoke commands menu?

### ISSUE THREAD

**Issue by linux-china** [dploeger/idea.shellfilter#1]
it will be convenient with a shortcut to invoke commands menu, then insert the content of selected command.

**Comment by dploeger** [comment]
Yes, I thought about that, but couldn't find a valid default shortcut that is working on all supported OSes. You can, however, map a key yourself using Settings/Keymap. You can find the Shell Filter actions under Main Menu/Edit.

Is that okay for you or would you still like a default shortcut? If so, what would you recommend?

**Comment by linux-china** [comment]
Now I use Alt+Command+I in Mac.  "Command" means command execution.  "Alt" just fixes shortcut conflict.  "I" means insert.

**Comment by dploeger** [comment]
That'd be a duplicate with "Auto-Indent lines" on my Mac...

**Comment by linux-china** [comment]
@dploeger  I choose "Mac OS X 10.5+" as keymap schema, and I think you choose "Mac OS X".    please try Ctrl+Command+I.

**Comment by dploeger** [comment]
That's my problem: I can't predict the keymap on the user side. But, basically, you're saying that not providing a default shortcut is something that should be changed?

If so, I will just use the Command+Alt+I shortcut. If the user doesn't want or can't use that, he/she has to set it themselves.

**Comment by linux-china** [comment]
Ctrl+Command+I is fine for mac user without conflict, and we can use this one as default shortcut.  :)

**Comment by dploeger** [comment]
Done in 1.0.1
