### ISSUE TITLE
Shortcut to go straight to custom

### ISSUE THREAD

**Issue by oscu0** [dploeger/idea.shellfilter#3]
I usually use very specific, one-time snippets - grep a file on a remote host, typically. I don't need to save commands - could we please get the ability to bind a key straight to custom?

**Comment by dploeger** [comment]
Currently, the default shortcut will open the command list, where you can speed search the desired command. But that isn't enough for you?

I suppose, that offering commands to the keymap feature of IntelliJ can be done in a plugin. I currently have no time to implement that, but PRs are welcome. 😄

**Comment by oscu0** [comment]
My point was that I don't have a list - I only ever use the 'Custom' option, which makes the list redundant. That's why I wanted a shortcut that takes you straight to command input - I didn't mean functionality to bind arbitrary saved commands, I should have phrased that better.

**Comment by dploeger** [comment]
Ah, okay. Understood.

**Comment by dploeger** [comment]
This is available in version 2.1.0
