### ISSUE TITLE
Does this plugin support Windows command? 

### ISSUE THREAD

**Issue by jyinpci** [dploeger/idea.shellfilter#4]
I would like to use this in Windows environment.  Will it work?  What should I use to replace /bin/sh ?

**Comment by dploeger** [comment]
Hm. That's a good question. I'm not so used to Windows, but it may work with things like the WSL or Git Bash. Maybe even with CMD.exe and powershell.

Basically, the plugin just calls any external program, sends the selected content to STDIN and pastes in what it receives on STDOUT. To my knowledge, Windows also supports these channels.
